### ISSUE TITLE
Bitcoin Wallet sidebox, features

### ISSUE THREAD

**Issue by schildbach** [JTuwiner/NoThirdParty#3]
1. In the "features" sidebox for Bitcoin Wallet, it lists "Private Key Import" which is not correct. By design, we don't import or export private keys. I suggest listing "Paper Wallet sweep" or "Sweep Paper Wallets" as that's the only feature that comes close.

2. BIP70 is very technical, I suggest using "Payment Protocol (BIP70)" or just "Payment Protocol". (might apply to other wallets too)

3. Maybe extend "Bluetooth Payments" to "NFC/Bluetooth Payments"?

**Comment by JTuwiner** [comment]
Updated with all of the changes suggested. These items are now more clear and easier to understand.
